### ISSUE TITLE
[Docs] We should explicitly call out the alpha-ness of v5

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1006]
I find the alpha symbol (`α`) a confusing way to convey the state of Keystone 5.

Looking at other projects such as [lodash](https://lodash.com/docs), [tailwind](https://tailwindcss.com/docs), [react](https://reactjs.org/docs/getting-started.html), and [`date-fns`](https://date-fns.org/v2.0.0-alpha.27/docs/Getting-Started) the version and (sometimes) the current state of the project is explicitly called out in the header to reduce ambiguity and increase developer's confidence they're on the right page for them.

I propose we replace the alpha symbol with the version number + the word `alpha`.

Currently looks like:

![Screen Shot 2019-04-08 at 11 45 15 am](https://user-images.githubusercontent.com/612020/55693696-ce9f9280-59f3-11e9-94da-efecb5df1816.png)

Proposed new look:

![Screen Shot 2019-04-08 at 11 44 51 am](https://user-images.githubusercontent.com/612020/55693700-d65f3700-59f3-11e9-9e90-69ffafc0de8c.png)

**Comment by jordanoverbye** [comment]
Happy to help with this one - but I'm not sure where the best place is to get the latest version of Keystone? I'm assuming `@keystone-alpha/keystone` package.json but that version is `15.2.1`.

So would it read `KeystoneJS` v5.15.2.1`?

@jesstelford are you able to help with this please 🙏

**Comment by jesstelford** [comment]
A literal `v5.x` is fine for now, no need to pull in actual version numbers or anything.

Thank you! 🙏
