### ISSUE TITLE
AdminUI: State update on unmounted component on first item creation

### ISSUE THREAD

**Issue by thiagodebastos** [keystonejs/keystone-5#1026]
## Steps to reproduce

1. `yarn create keystone-app myApp`
2. in myApp `yarn start`
3. Navigate to AdminUI in browser of choice
4. Create a new Todo

## Expected
No console errors

## Actual
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

**Comment by mitchellhamilton** [comment]
These are the broken lines if you want to submit a PR, these two lines need to be switched around so the setState call is first.

https://github.com/keystonejs/keystone-5/blob/b9759f8f32efcb14d5ceaca0a0f64ea702905311/packages/admin-ui/client/components/CreateItemModal.js#L44-L45

**Comment by thiagodebastos** [comment]
> These are the broken lines if you want to submit a PR, these two lines need to be switched around so the setState call is first.
> 
> [keystone-5/packages/admin-ui/client/components/CreateItemModal.js](https://github.com/keystonejs/keystone-5/blob/b9759f8f32efcb14d5ceaca0a0f64ea702905311/packages/admin-ui/client/components/CreateItemModal.js#L44-L45)
> 
> Lines 44 to 45 in [b9759f8](/keystonejs/keystone-5/commit/b9759f8f32efcb14d5ceaca0a0f64ea702905311)
> 
>  this.props.onCreate(data); 
>  this.setState({ item: this.props.list.getInitialItemData() });

Thanks @mitchellhamilton , I'll do that now.

**Comment by dcousens** [comment]
Fixed in 5b9022b
