### ISSUE TITLE
Decide on Direct Property Access vs Getters

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1055]
Throughout the codebase we are using two different patterns for accessing data on classes & objects:

## Direct property access

[For example](https://github.com/keystonejs/keystone-5/blob/5e0a1c2c88898b8c7d3c5d91d514012589a62b12/packages/adapter-knex/lib/adapter-knex.js#L130).

```javascript
class BaseFieldAdapter {
  constructor(/* ... */, { isRequired, isUnique, ...config }) {
    this.isRequired = isRequired;
    this.isUnique = isUnique;
  }
  // ...
}

// elsewhere:
if (adapter.isUnique) {
  // Do a thing
}
```

## Getters

https://github.com/keystonejs/keystone-5/blob/5e0a1c2c88898b8c7d3c5d91d514012589a62b12/packages/fields/src/types/CloudinaryImage/Block.js#L9-L11

https://github.com/keystonejs/keystone-5/blob/5e0a1c2c88898b8c7d3c5d91d514012589a62b12/packages/fields/src/Implementation.js#L62-L64

## Discussion

It'd be good to settle on one or the other style of accessing data.

In some cases, there are getters in use which dynamically generate their data, so it makes sense to be a _Getter_, but then should it be a function invocation, or a class `get X()` getter?

**Comment by jesstelford** [comment]
Personally, I prefer the explicitness of a function invocation (`foo.getType()`).

**Comment by dcousens** [comment]
Is there any expectation that the value will change or is lazily calculated?  Then maybe `getType`.
Otherwise, a read-only constant.

**Comment by JedWatson** [comment]
IMO we should use property access where possible. Especially for config / immutable values calculated in the constructor, etc.

We had quite a few instances in keystone 4 where values were lazily calculated, and used getters for that. I'm in favor of using getters in those circumstances.

However, for anything that's going to be read on startup we need to be careful that we're actually making valid optimisations, and not writing lazy getters for stuff that's going to be almost immediately calculated anyway (keystone 4 did some of this as well). Better to initialise in the constructor if that's the case, and simplify things.

If a value is mutable or dynamic, we should use actual functions.

**Comment by jesstelford** [comment]
I think the conclusion here is; there's no right or wrong way to use getters vs functions vs class properties 👍 

Thanks for the input folks!
