### ISSUE TITLE
Replace 'Jade' to 'Pug' for EmailSender

### ISSUE THREAD

**Issue by ticidesign** [keystonejs/keystone-5#1058]
Replace the email renderer as 'Jade' was renamed to 'Pug'. 
All the major version will now carry "pug" as the package name:
https://www.npmjs.com/package/pug

https://github.com/keystonejs/keystone-5/blob/master/packages/email/package.json#L23

**Comment by w01fgang** [comment]
Waiting for the review and merge #1063
