### ISSUE TITLE
Hide label column in administration UI

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1072]
When I have provided a `labelResolver` for a schema item,  it oftentimes mirrors another field.

``` js
{
  labelResolver: x => x.name,
  name: { type: Text, isUnique: true },
  ...
}
```

Is there a way to hide `label` from showing in the administration interface (as both `name` and `label` are equivalent).

**Comment by dcousens** [comment]
Possibly resolvable with https://github.com/keystonejs/keystone-5/issues/979

**Comment by MadeByMike** [comment]
I'd say a set of default cols is the way to solve this. Closing as dupe of: #979

**Comment by karmux** [comment]
Issue still persists. Setting defaultColumns doesn't hide Label column.

**Comment by gioravered** [comment]
Any news about this issue?
