### ISSUE TITLE
Schema type validation

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1135]
Using [`typeforce`](https://www.npmjs.com/package/typeforce) or similar,  it would be nice to have type validation against the user provided schemas to prevent confusion and errors on part of the developer.

Could resolve https://github.com/keystonejs/keystone-5/issues/549 (partly) in a breaking way, but,  better than silently ignoring it.

A first pass at a `typeforce` schema validation schema (ha) is something I use for myself

``` js
    const tf = require('typeforce')

    tf(tf.map({
      type: {
        type: tf.String,
        implementation: tf.Function,
        views: {
          Controller: tf.String,
          Field: tf.String,
          Filter: tf.String
        },
        adapters: tf.map(tf.Function)
      }
    }), sanitisedFieldsConfig)
```

Injected into `initFields` in packages/keystone/lib/List/index.js

**Comment by MadeByMike** [comment]
I think this fits in the larger types discussion. See: #1323 and #1373
