### ISSUE TITLE
Password confirmation does not confirm password

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1139]
Ignoring the fact that password validation errors (e.g password too short) errors are not shown at all (probably related to https://github.com/keystonejs/keystone-5/issues/433).

The confirm password field does not actually confirm anything.

Reproduction steps:
- Enter a password `password`
- Enter a confirmation password `foo`
- Save (and watch it succeed)

**Comment by Vultraz** [comment]
Can't reproduce this one either. 🤔
