### ISSUE TITLE
Non-stop renders

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1141]
Watch your CPU usage rise as `React` renders/refreshes as quickly as it can (or close too it) when viewing any List in Keystone.

**Steps to reproduce**
- `yarn start blog`
- http://localhost:3000/admin/users

The closest I got to a debug trace at this point was watching https://github.com/keystonejs/keystone-5/blob/51e7330abe22d1f3cf2d5babedcb0ce37b54b564/packages/admin-ui/client/pages/List/url-state.js#L56 being called over 100,000 times as it crashed my browser when I put a `console.log` in there.
 
If you can't *feel* the above,  try that.

**Comment by jesstelford** [comment]
That's bad.
