### ISSUE TITLE
Mongoose adapter requirements Mongo v3.6 or later; not documented

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#1154]
It seem the Mongoose adapter requires version 3.6 or later of Mongo. Generally this seems like a reasonable requirement -- v3.6 was released 2017-10-02; v4.0 was released 2018-06-27.

When querying, Mongo v3.4 gives the errors like:

```
MongoError: arguments to $lookup must be strings, let: { xxxxx: \"$xxxx\" } is type object
```

This [Stackoverflow thread](https://stackoverflow.com/questions/47669976/mongodb-aggregate-arguments-to-lookup-must-be-strings) covers the same issue.

Proposed fixes:

* [ ] Update the main README.md to note the version requirement
* [ ] Update the `adapter-mongoose` package README.md to note the version requirement
* [ ] Check the version on start up and warn or error?

**Comment by jesstelford** [comment]
The required version is >=v4.

We have it on the documentation website already:

<img width="919" alt="Screen Shot 2019-05-15 at 12 19 24 pm" src="https://user-images.githubusercontent.com/612020/57744236-c2ea6e80-770b-11e9-8d20-b5c08105e600.png">

**Comment by dcousens** [comment]
Maybe relevant to [point out that `4.0.3`](https://en.wikipedia.org/wiki/MongoDB#Licensing) is the _last_ stable AGPL (open-source licensed) version of Mongodb to be released.

**Comment by jesstelford** [comment]
Closing as we have the requirements documented on the website & the `README.md` now.
