### ISSUE TITLE
How do we code snippets?

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone-5#1175]
Was looking at the code snippet in: https://v5.keystonejs.com/keystone-alpha/fields/src/types/date-time/

which documents how to use it with the code snippet

```javascript
keystone.createList('User', {
  fields: {
    email: { type: Text },
    password: { type: Password },
    lastOnline: {
      type: DateTime,
      format: 'MM/DD/YYYY h:mm A',
      yearRangeFrom: 1901,
      yearRangeTo: 2018,
      yearPickerType: 'auto',
    },
  },
});
```

There's a bunch of stuff here that's imported that we don't show where we import it from, with `keystone` and `Password`, but also `DateTime` itself. This makes this code snippet a bit unclear, but this seems to have been the pattern through writing these snippets.

Was wondering if we would be open to having these be the more complete

```javascript
const { Text, Password, DateTime } = require('@keystone-alpha/fields');

keystone.createList('User', {
  fields: {
    email: { type: Text },
    password: { type: Password },
    lastOnline: {
      type: DateTime,
      format: 'MM/DD/YYYY h:mm A',
      yearRangeFrom: 1901,
      yearRangeTo: 2018,
      yearPickerType: 'auto',
    },
  },
});
```

This becomes extra significant if we split some blessed fields out of the core fields package (glaring at you cloudinaryImage).

If this is something we're interested in, happy to do this as a quick change.

**Comment by jesstelford** [comment]
Yep, we should include the imports too. Possibly even the construction of the `keystone` object:

```javascript
const { Text, Password, DateTime } = require('@keystone-alpha/fields');
const { Keystone } = require('@keystone-alpha/keystone');

const keystone = new Keystone(/* ... */);

keystone.createList('User', {
  fields: {
    email: { type: Text },
    password: { type: Password },
    lastOnline: {
      type: DateTime,
      format: 'MM/DD/YYYY h:mm A',
      yearRangeFrom: 1901,
      yearRangeTo: 2018,
      yearPickerType: 'auto',
    },
  },
});
```
