### ISSUE TITLE
Unable to remove relationships in AdminUI

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone-5#1185]
When I remove I user from the speakers relationship and click save, the user does not get removed

![90CbDF1Dgw](https://user-images.githubusercontent.com/42298774/57909295-c32e6980-78c5-11e9-9b8a-68a23d98870a.gif)

**Comment by jesstelford** [comment]
Looks like we've not implemented the usage of `disconnect: [{ "id": "abc" }]` in the admin UI.

**Comment by sresidovic** [comment]
Further context: removing all speakers and saving seems to work.

**Comment by jesstelford** [comment]
Should be fixed in latest release: https://github.com/keystonejs/keystone-5/pull/1366
