### ISSUE TITLE
Installing dependencies in create-keystone-app fails

### ISSUE THREAD

**Issue by w01fgang** [keystonejs/keystone-5#1187]
Creating an app fails after this command: `yarn create keystone-app keystone-migration`
with this error:
```
✔ Check ./keystone-migration
✔ Create KeystoneJS Project
✖ Install dependencies with Yarn
    → spawn yarnpkg ENOENT
```
because [here](https://github.com/keystonejs/keystone-5/blob/master/packages/create-keystone-app/lib/generator.js#L70) it spawns `yarnpkg` instead of `yarn`

**Comment by w01fgang** [comment]
yarnpkg is an alias of yarn, no idea why it didn't work

**Comment by jesstelford** [comment]
Hmm 🤔 And if you run `yarnpkg` in that directory, it works?

**Comment by w01fgang** [comment]
@jesstelford sorry, this time I was too fast to open the issue.
I don't know why it didn't work from the beginning, but now it works as expected 🤷‍♂
Could be an issue unrelated to create-keystone-app.
Next time I'll investigate more before opening an issue.
Thank you!

**Comment by jesstelford** [comment]
Not a problem. Glad it's working 🎉
