### ISSUE TITLE
Extending File field type can throw field-views-error

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1218]
Will throw an error:

`index.js`

```javascript
const { File } = require('@keystone-alpha/fields');
module.exports = {
  views: {
    Cell: File.views.Cell, // works
    Filter: File.views.Filter, // throws an error
  }
};
```

But if we omit the `Filter` view, it works. It's because `File.views.Filter` is `undefined`. This implies the field-views-loader is handling these two cases differently:

```json
{
  Filter: undefined
}
```

```json
{
}
```

(ie; a key with value undefined, vs an undefined key).

**Comment by JedWatson** [comment]
@mitchellhamilton could you take a look at this? might be a quick fix (or not)
