### ISSUE TITLE
Custom list labels

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1219]
``` js
keystone.createList('InternalTodosList', {
  adminUiLabel: 'My TODO list',
  fields: {
    ...
  }
})
```

As is,  I am stuck with the administration UI showing `Internal Todos List` on the dashboard.

**Comment by timleslie** [comment]
If you replace `adminUiLabel` with `label` in your example you should get what you want. Let me know if that doesn't work out.
