### ISSUE TITLE
isRequired has no effect

### ISSUE THREAD

**Issue by dcousens** [keystonejs/keystone-5#1245]
``` js
  fields: {
   description: {
     type: Text,
     isRequired: true
   }
  }
```

Expectation is that it fails if `null` (or `''`, aka empty string) in the administration UI on creation.

Actuality: It creates an item without an error.

**edit:** Unclear if this is meant be enforced by GraphQL,  but,  I can verify that you can `create*` `isRequired` fields as `null` without error too.  `isUnique` **is** enforced by GraphQL.

**Comment by timleslie** [comment]
Definitely a bug. I'm working on writing this now, starting with writing a bunch of unit tests so we can have visibility about whether `isRequired` is working across all of our field types.
