### ISSUE TITLE
Integrate GraphiQL Explorer 2.0

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1267]
See https://www.onegraph.com/blog/2019/05/30/GraphiQL_Explorer_2_0_A_Power_User_Release.html

**Comment by MadeByMike** [comment]
@jesstelford I'd like to close this as `wont-fix` the new explorer looks cool but I see no pressing reason to add it to Keystone. I think people are familiar with the playground, and it works great. 

It's not that it is a bad idea, just one more integration that we'd have to support. I want to clean house a little and make a decision about some ideas that we know we are not going to get.

No reason people can't add this to their own projects however.
