### ISSUE TITLE
Docs: generated ToC links is not working propertly on website

### ISSUE THREAD

**Issue by uniconstructor** [keystonejs/keystone-5#1271]
A small problem with doc generation: the links from table of contents section works fine in github pages, but didn't work on project website.

Example:
1) github doc page (ToC links is OK): https://github.com/keystonejs/keystone-5/blob/master/docs/discussions/mutation-lifecycle.md
2) same page on keystone's 5 website (ToC links is broken): https://v5.keystonejs.com/discussions/mutation-lifecycle

(Looks like a problem with a docs generation script)

**Comment by jesstelford** [comment]
Thank you 🙏 

Looks like titles with some non-alpha-num characters are broken:

```
/discussions/mutation-lifecycle#1-check-list-access-create-update-delete - CORRECT
/discussions/mutation-lifecycle#1-check-list-access-createupdatedelete - WRONG (TOC link)
```

The titles themselves have the correct links, but the TOC doesn't.

**Comment by BarryThePenguin** [comment]
I think this is fixed now? Can close this issue 👍

**Comment by uniconstructor** [comment]
Checked out doc links, they all are fixed now. Closing issue.

**Comment by 1337cookie** [comment]
This may be still be an issue. Links work on github but not website docs. Is there a specific way we should link to other docs pages? 
Eg. https://v5.keystonejs.com/guides/add-lists

**Comment by thiagodebastos** [comment]
I just noticed the same issue today with links in https://v5.keystonejs.com/discussions/schema.

1. link to `createLists()` API:
```diff
- https://v5.keystonejs.com/discussions/api/create-list
+ https://v5.keystonejs.com/api/create-list
```

1. Link to quickstart
```diff
- https://v5.keystonejs.com/discussions/quick-start
+ https://v5.keystonejs.com/quick-start
```
