### ISSUE TITLE
Test framework expects all field types to support all adapters

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#1335]
I get that we want all core field types to support all core database adapters but, until we get there, can we make it so the test suite doesn't assume this is the case?

**Comment by jesstelford** [comment]
This _is_ the case today; otherwise the tests wouldn't be passing.

Is there a specific use-case you have in mind for a core field type not supporting a core database adapter?

**Comment by molomby** [comment]
Ha, quite right. I want to add a type for UUIDs.

Knex/pg support is easy; they're stored in a binary format and implicitly cast between it and Strings on the way in and out of the DB.

Without a fair bit of effort, Mongoose/Mongo will treat them as Strings. This bloats the DB and breaks equality comparisons due to case sensitivity. Supporting them _properly_ for Mongo requires explicitly converting them to and from a binary type whenever they move in or out of the DB.

It's totally doable -- I'd love UUIDs (and all core types) to be fully supported -- I just don't want to do it today :)

This is part of a larger plan to make UUIDs the default id type for lists using the Knex adapter (or at least a core option). That what's stopping me from pulling this out into a non-core package, etc.

**Comment by molomby** [comment]
Uuids added in #1372 with basic Mongoose support
