### ISSUE TITLE
created object does not appear in drowpdown if removed , deleted objects appear in dropdown if previously linked

### ISSUE THREAD

**Issue by Olya-Yer** [keystonejs/keystone-5#1354]
if I create object as a field, I can't see it in drop down
![existing_fields](https://user-images.githubusercontent.com/33322677/60587905-a7fcb800-9da6-11e9-9281-7b80e0e51a4b.gif)

I can see deleted objects in dropdown 

![deleted_fields](https://user-images.githubusercontent.com/33322677/60587914-ae8b2f80-9da6-11e9-92b6-e9cd1f3e0f32.gif)

**Comment by jesstelford** [comment]
Great catch! This looks like a caching issue where we're not correctly clearing out deleted data / correctly re-querying after adding data.

**Comment by MadeByMike** [comment]
I can't reproduce. Looks like this has been resolved.
