### ISSUE TITLE
alternative to dependsOn from v4, conditional fields

### ISSUE THREAD

**Issue by Olya-Yer** [keystonejs/keystone-5#1355]
is there a way to show a field depending on value of other field?
in v4 I could do

```
Field.add({
  valueType: {
    type: Types.Select,
    numeric: true,
    options: [{ value: 1, label: 'String' },
              { value: 2, label: 'Blob' },
              { value: 3, label: 'Integer' }]
  },
  howMany: {
    type: Integer,
    dependsOn: { valueType: 4 }
  },
})
```

**Comment by jesstelford** [comment]
We don't yet have a [`dependsOn` option](https://v4.keystonejs.com/api/field/options/), but we've captured some initial ideas in #312. I'll mention `dependsOn` there so we can keep track 👍
