### ISSUE TITLE
GraphQL API not returning duplicate related items

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1364]
For example, if you add the same related item multiple times, the GraphQL API will uniquify the related items thereby hiding the duplicates.

This was tested on the mongodb adapter.

**Comment by JedWatson** [comment]
I'm just going to point out that I'm not sure this is actually _the_ bug. Unless we're going to support storing duplicate IDs in relationships properly (which would require quite a bit of work and testing) I think we should fail validation if duplicate IDs are connected.

Right now it _only sort of works_ and there's work to be done in the Admin UI as well before it works reliably. Until there's a clear use case / need, we could go the other way and not support duplicate IDs in relationship values at all.

**Comment by jesstelford** [comment]
Closing as duplicate of #288
