### ISSUE TITLE
Font license for Neue Haas Unica Pro in meetup

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1367]
I see the font `Neue Haas Unica Pro` is used in meetup demo project. 
Is this font ready to be used with other projects, given that it is a paid font (quick search reveals that). 

This demo is also being used to power SydJs website, if this font was licensed to use with SydJs then we should either 

remove this font and let others use their own while this font is integrated with the SydJs deployment pipeline, 
OR
add some description on usage of this font by others.

**Comment by jesstelford** [comment]
Good catch! We should remove this entirely from the Keystone5 codebase as it's a licensed font.

**Comment by JedWatson** [comment]
Thanks for catching this @gautamsi!
