### ISSUE TITLE
Cache Control Hints

### ISSUE THREAD

**Issue by sarneaud** [keystonejs/keystone-5#1453]
Hi,

I need to configure `Cache-Control` headers for better performance.  I'm trying to hack it with custom middleware for now, but it really should be done with schema-level hints like this:
https://www.apollographql.com/docs/apollo-server/features/caching/

Some use cases:

* Adding `Cache-Control: private` to anything that depends on the authenticated user or other access control (critical to avoid leaking sensitive data through CDNs)
* Configuring a global default `maxAge`
* Configuring `maxAge` and `private/public` at the list level (very nice to have)
* Configuring cache hints at the field level (wishlist)

Support for `Vary` would be great, too, but Apollo has an open request ticket for that: https://github.com/apollographql/apollo-feature-requests/issues/142

**Comment by timleslie** [comment]
Maybe (very roughly) something like this?

```javascript
  wrapFieldResolverWithAC(field, innerResolver) {
    return (item, args, context, info) => {
      // If not allowed access
      const operation = 'read';
      const access = context.getFieldAccessControlForUser(this.key, field.path, item, operation);
      if (!access) {
        // If the client handles errors correctly, it should be able to
        // receive partial data (for the fields the user has access to),
        // and then an `errors` array of AccessDeniedError's
        this._throwAccessDenied(operation, context, field.path, { itemId: item ? item.id : null });
      }
      if (field.config.cache.maxAge) {
        info.cacheControl.setCacheHint({ maxAge: field.config.cache.maxAge, scope: 'PRIVATE' });
      }
      // Otherwise, execute the original/inner resolver
      return innerResolver(item, args, context, ...rest);
    };
  }
```

**Comment by sarneaud** [comment]
Added in https://github.com/keystonejs/keystone-5/pull/1686
