### ISSUE TITLE
Mongoose Database Adapter page is out of date

### ISSUE THREAD

**Issue by jordanoverbye** [keystonejs/keystone-5#1457]
Reference: https://v5.keystonejs.com/keystone-alpha/adapter-mongoose

1. The `mongoDbUri` section on this page should be removed or updated as this is not how you set the URI of the database connection. This is set via the `CONNECT_TO` env variable or `-connect-to` cli switch.

2. The code example in `Usage` is also out of date.

**Comment by MadeByMike** [comment]
@jordanoverbye Thanks so much! We are in Alpha and things are changing frequently so sorry this is out of date. You're right in noting that that the docs need some attention and we're going to starting a big push on this soon.

For now, I've made a PR to update the example you've pointed out: https://github.com/keystonejs/keystone-5/pull/1458

Thanks so much for helping us!

**Comment by MadeByMike** [comment]
Fixed in #1468
