### ISSUE TITLE
`createItems` can only be run after `onConnect`

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone-5#1478]
Running `keystone.createItems` like this works fine:

```
const keystone = new Keystone({
  name: 'example',
  adapter: new Adapter(),
  onConnect: async () => {
    keystone.createItems({
      User: [
        {
          name: "Admin",
          email: "admin@keystonejs.com",
          password: "correcthorsebatterystaple"
        }
      ]
    });
  }
});
```

However if you try to do this outside `onConnect` an error is thrown.

It should be simple enough to make this work without this requirement.

**Comment by jesstelford** [comment]
`createItems()` is a task which requires having a working database connection, and all the information about the database schema. It's not possible to have that until after we're connected (ie; we've run `keystone.connect()`. The `onConnect` callback is run specifically after the `keystone.connect()` call for this purpose.

I'm going to close this issue as `wontfix` as there's no way to make it happen.

There is also a related issue for better error messages when trying to do things before `keystone` is ready: https://github.com/keystonejs/keystone-5/issues/1081
