### ISSUE TITLE
Link to edit docs for Keystone 5 on Github is broken

### ISSUE THREAD

**Issue by leopoldkristjansson** [keystonejs/keystone-5#148]
Example link: https://www.keystonejs.com/keystonejs/keystone/#sessionstore

![Screen Shot 2021-05-13 at 13 17 02](https://user-images.githubusercontent.com/2579324/118119593-e3c72680-b3ee-11eb-8b30-c41a07020904.png)

**Comment by bladey** [comment]
Thanks @leopoldkristjansson! A site deploy was held up, fixed!
