### ISSUE TITLE
Singular and Plural options are not used in some places in adminUI

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone-5#1493]
![image](https://user-images.githubusercontent.com/1320567/62988116-79cec580-be86-11e9-9e1a-05dac5851075.png)

Config is:
```
keystone.createList("WoolyBoi", {
  schemaDoc: "A list of things which need to be done",
  fields: {
    sheepName: { type: Text }
  },
  singular: "Sheep",
  plural: "Sheep"
});
```

I don't expect to see Wooly Bois.

**Comment by Vultraz** [comment]
Guessing [this line](https://github.com/keystonejs/keystone-5/blob/master/packages/app-admin-ui/client/components/Nav/index.js#L152) should be `node.plural` but cannot test to confirm.
