### ISSUE TITLE
Ability to modify list after `keystone.createList` is called

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1498]
There are some scenarios where a custom plugin or package which make use of keystone instance may want to add another field or modify features of List like mutations. In current implementation it is not possible. 

proposing:

**`List.addField` or `addFields`** : This can be helpful to add another field which can be used to add and process field (`what `initFields` does) after the list creation. 

**`List.addMutations`**: adds new mutations, this would enable new scenario like custom mutations to be used with Admin UI extensibility (#1489 ) .

**'addHooks`** would also be helpful.

```js
keystone.createList('User', {......});

const userlist = keystone.getListBykey('User');
userlist.addFields({...filedConfig});
userlist.addMutations(....);
```

another quirky way is to delay call to `list.initFields` untill just before `keystone.connect` and tweak the list config similar to the list constructor, but that would not be good developer experience

**Comment by timleslie** [comment]
I'm still not sure what the use case here is and why it can't be achieved in user land, could you give a concrete example so I can better understand?

**Comment by MadeByMike** [comment]
What we're really asking for here is an imperative API in addition to the declarative API. I'd say that adding that soon is not a priority, but I'm happy to keep this issue around to capture any situations that might come up 👍 

@gautamsi - I can imagine some situations where this might be useful but none that don't have alternatives at the moment. This might prove a good idea in the future, but w're trying not to anticipate future needs too much as they change a lot.

**Comment by gautamsi** [comment]
@timleslie  simple example: 
Social Logins: currently you have to add a field in `User` schema and provide that in constructor of Auth strategy (google, twitter etc.)

if you do not pass the field, or this does not exist on `User` schema the social logins will break

Once this feature makes a way in, Social Login strategy can add that field themselves. 

Similar changes can be done with user land packages. 

modifying a list after `createList` is called may not work or would not be optimal, even in user land as the list does not expose proper way to do that. 

> why it can't be achieved in user land

`createList` calls list constructor and `list.initFields` which does validation and sanitisation. at this point I do not know if there is a way to modify fields or any other configs.

@MadeByMike declarative is  good but that should compliment imperative and not abrogate it completely. that is why I am struggling to find ways to properly modify the list after the constructor is called.

Another good features would be to pre-prep  the list by user land package, more details in new issue later.

**Comment by MadeByMike** [comment]
I think everything we want to do here is now captured by the list-plugins which were added partially to address the ability to package extensions to lists. 

We don't really want to change the current API. I think the way forward with this is to raise any new issues related to missing functionality or desired outcomes. 

At the moment this is a solution without a problem and it's not a solution we're considering at the moment so I am going to close this one until there is a better use-case.
