### ISSUE TITLE
There is no way to add custom graphQL types to the graphQL schema 

### ISSUE THREAD

**Issue by SeanDoyleGit** [keystonejs/keystone-5#1502]
When I am creating custom mutations in a keystone list, there is no way to define a new graphQL type to return the necessary data from the mutation. 

e.g. 
I would like to be able to define a type `MyCustomType`

```
mutations: [
  {
    schema: 'test(email: String!): MyCustomType',
    resolver: async (obj, args, context, info, { query }) => {
      //run DB query to get data 
      //return data in the format of MyCustomType
    },
  },
],
```

**Comment by jesstelford** [comment]
Happy to add a `getGqlAuxTypes` config option for lists, which could then be consumed in https://github.com/keystonejs/keystone-5/blob/master/packages/keystone/lib/List/index.js#L345

For now, you can return a `JSON` type for complex data.

**Comment by SeanDoyleGit** [comment]
solved by https://github.com/keystonejs/keystone-5/pull/1503
