### ISSUE TITLE
GraphIQL: Server cannot be reached

### ISSUE THREAD

**Issue by Nakzz** [keystonejs/keystone-5#1550]
Following the[ Getting Started guide](https://v5.keystonejs.com/quick-start/) I have initialized my project, however, in the GraphQL playground I am getting the following error- Server cannot be reached
```

{
  "error": "Response not successful: Received status code 400"
}
```
The database is running, and I can access the admin UI. Also, is there any documentation on how to access the API that is generated by Keystone?

**Comment by MadeByMike** [comment]
Hi Nakzz, `400` usually means forbidden, so it looks like you might have access controls configured but are trying to access a list or field without required permissions or without logging in?

If you could share your `createList` code this would be helpful. The best place to do this is probably to jump over to our Slack community: https://launchpass.com/keystonejs

**Comment by Nakzz** [comment]
I fixed the issue by adding a custom server and enabling cors.
