### ISSUE TITLE
How to use a bundler like parcel or webpack with keystone 5

### ISSUE THREAD

**Issue by gabalicious** [keystonejs/keystone-5#1558]
Sorry if this isn't right way to post this.  I wasn't sure where what the best place was.

I'm looking to have the Keystone app serve up the frontend dist folder for a React/Vue app which I've bundled using parcel.   

I've been playing around with the alpha release and i wasn't sure how to have keystone serve up my frontend.  Here's what the `index.js` file for the keystone app looks like. 

```
module.exports = {
  keystone,
  apps: [
    new GraphQLApp(),
    new StaticApp({
      path: "/",
      src: "frontend_dist",
      fallback: "index.html"
    }),
    new AdminUIApp({ enableDefaultRoute: true })
  ]
};
```

Here's roughly what the rest of my app looks like right now.

```
├── dist
│   └── admin
├── frontend_dist (bundled using parcel command)
│    ├── index.html
│    └── bundle.js
├── index.js
├── package.json
├── public
│   ├── apple-icon.png
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
├── src
│   ├── assets
│   ├── components
│   ├── index.html
│   ├── main.js
│   ├── variables
│   └── views
└── yarn.lock
```

Right now when go to `localhost:3000` it just show welcome to Keystone page.

I'd love to help contribute to this project with documentation and sample projects.  I've been reading through issues labeled as `good first issue`.  And if there's a better place to continue this discussion I'll be happy to post there.

**Comment by MadeByMike** [comment]
Hi Gabalicious,

At the moment the Static App just serves a directory and it doesn't mind how that code is bundled. The Static App as a good starting point to build and launch a front-end in conjunction with Keystone. One start command etc... but in many cases it is expected that you would 'eject' out of this model (especially in the case of static front-end applications) and host the front end on a different server and perhaps in a different repository.

I've been thinking a lot about how we can best help people building JAMStacks using React\Vue\Angular etc... and I think I'd like to do more. One part is to write a good explanation of using the Static App and how to "Eject" as your front-end project grows and this becomes a requirement. Another part is to build a React App / Vue App etc... that provides out of the box build processes and bundling like you mention. 

I'd LOVE to work with you on this. Would you like to jump on our community Slack and say hi? http://community.keystonejs.com/ - looking forward to hearing your ideas.

**Comment by gabalicious** [comment]
Ok so I tried it out today and I was able to get a sample parcel frontend app to work rather with keystone 5 effortlessly.

**Comment by MadeByMike** [comment]
Glad to hear it! I've also been working on a Nuxt.js app with @simonswiss and I have started a React app. Next step is the documentation on moving out of these.

I'm going to close this issue as I think we've made a good start on this and captured the steps.
