### ISSUE TITLE
@keystone-alpha/apollo-helpers - roadmap?

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1565]
is this still on roadmap? I don't see any usage with any demo. possibly needed to drop it from packages.

**Comment by MadeByMike** [comment]
It's been discussed. It might move out of the mono-repo eventually as it's not closely tied to Keystone (I think in theory it could be used without it). Decision was to leave it alone for now 😆 It's doing no harm and we have enough other things to focus on 👍
