### ISSUE TITLE
Make `keystone.sid` cookie secure in Prod mode

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1595]
We automatically set the `keystone.sid` cookie when performing an `authenticate<List>with<Strategy>`, but it's not set to `secure`. We should set it to `secure: true` when `NODE_ENV === 'production'`.

See: https://www.npmjs.com/package/express-session#cookiesecure

**Comment by MadeByMike** [comment]
Fixed in #1612
