### ISSUE TITLE
Weird errors working with demo project

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone-5#1600]
1. Create a new project with `yarn create keystone-app foo`. Select Starter and mongoose.
2. Add a `StaticApp` instance to the apps list and try to run the project (`npm run dev`). It will fail.
3. Install `StaticApp` (`npm i @keystone-alpha/app-static`)
4. Try `npm run dev` again. You'll get an error saying the `@keystone-alpha/fields` package isn't installed, which makes no sense since the fields package is included right in the demo.
5. Install the fields package (`npm i @keystone-alpha/fields`)
6. Run `npm run dev` again. This should appear.
```
× Initialising Keystone instance
No 'id' field given for the 'User' list and the list adapter in used (User) doesn't supply a default primary key config (no 'getDefaultPrimaryKeyConfig()' function)
```

Is this some weird interaction between the yarn-generated project and packages installed with npm?

**Comment by MadeByMike** [comment]
@Vultraz the `cli` will install dependencies using yarn if it detects it. If you `npm` install something after that it I imagine it could be an issue. Do you experience the same error if you:

1. Delete the `node_modules` directory and re-install dependencies with either `yarn` or `npm`?
1. Follow the steps above and install the `@keystone-alpha/app-static` with yarn?

**Comment by Vultraz** [comment]
Tried both. Everything works after either reinstalling all packages with npm or initially installing `app-static` with yarn. Should probably mention this in the docs somewhere.

**Comment by MadeByMike** [comment]
Awesome I'm going to close this one. It should create a `yarn.lock` file, but I might also change the `cli` text to read "installing dependencies with yarn" or something like that.
