### ISSUE TITLE
Docs for keystone.prepare should mention it returns a promise

### ISSUE THREAD

**Issue by Vultraz** [keystonejs/keystone-5#1606]
The docs for `keystone.prepare` don't mention it returns a promise. You need to look at the Custom Server page for that. It's also not immediately clear on that page that `middlewares` is the returned object property name, not an arbitrarily chosen variable name.

**Comment by jesstelford** [comment]
Great catch!

If you're able, it'd be great to see a PR which updates these docs. The easiest way is to click the "Edit" button at the bottom of the specific page on v5.keystonejs.com 👍
