### ISSUE TITLE
Update Prisma CLI to latest

### ISSUE THREAD

**Issue by Jolg42** [keystonejs/keystone-5#161]
I see that the version is a bit old now `2.16.1`
https://github.com/keystonejs/keystone-5/blob/main/packages/adapter-prisma/package.json#L17

In the latest version, Prisma Migrate and db push are GA and no Preview flag is needed anymore.

Also, you could make these 2 lines one, that would be faster to execute
https://github.com/keystonejs/keystone-5/blob/439b0603354e6308bc0dbc2a54989f417554f995/packages/adapter-prisma/lib/adapter-prisma.js#L250-L252

and replace by
```
this._runPrismaCmd(`db push --force-reset`);
```
See https://www.prisma.io/docs/reference/api-reference/command-reference#db-push

**Comment by bladey** [comment]
Hey @Jolg42,

We'd be happy to review a PR for this if you'd like to submit one! We're currently focused on [Keystone Next] and have Keystone 5 in maintenance mode, so won't be working on major changes such as the one above at this time.

**Comment by Jolg42** [comment]
Oh ok! I misunderstood and thought this was the "new" repo for "Next".

All good to me to focus on https://github.com/keystonejs/keystone 👍 

Feel free to close this.
