### ISSUE TITLE
`npm init keystone-app my-app` fails if you don’t have yarn installed

### ISSUE THREAD

**Issue by dzigg** [keystonejs/keystone-5#1616]
Followed the docs on creating a todo app ~ `https://v5.keystonejs.com/quick-start/`
Failed after "Copying project files"
![Screen Shot 2019-09-11 at 1 37 03 pm](https://user-images.githubusercontent.com/4436922/64666378-75072c80-d499-11e9-824a-121783d30615.png)

Ran `npm install` to install dependencies and the app worked fine.

**Comment by MadeByMike** [comment]
Thanks @dzigg it's meant to catch an error if `yarn` is not installed and fallback to `npm`. Let me see if I can replicate this :)

**Comment by MadeByMike** [comment]
![image](https://user-images.githubusercontent.com/1320567/64667813-76872380-d49e-11e9-9f79-dcf5060dcbba.png)

I found the cause and updated the messaging so that you know if dependencies have been installed with yarn or npm.

Thanks @dzigg PR incomming

**Comment by dzigg** [comment]
Thanks!

**Comment by dzigg** [comment]
Thanks!

**Comment by masonmonu** [comment]
Hi all, npm init keystone-app my-app is failing.
