### ISSUE TITLE
npm run dev throws typeerror

### ISSUE THREAD

**Issue by hkovacs** [keystonejs/keystone-5#1653]
node v10.16.3
mongo v4+
npm v6.9.0
yarn v1.17.3
ubuntu 18.04

package.json 
{
  "name": "@keystone-alpha/example-projects-starter",
  "description": "An example KeystoneJS project with a User list and Authentication.",
  "private": true,
  "version": "1.1.6",
  "author": "The KeystoneJS Development Team",
  "license": "MIT",
  "engines": {
    "node": ">=8.4.0"
  },
  "scripts": {
    "dev": "cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev",
    "build": "cross-env NODE_ENV=production keystone build",
    "start": "cross-env NODE_ENV=production keystone start"
  },
  "dependencies": {
    "@keystone-alpha/adapter-mongoose": "^4.0.0",
    "@keystone-alpha/app-admin-ui": "^5.2.0",
    "@keystone-alpha/app-graphql": "^6.3.1",
    "@keystone-alpha/fields": "^10.2.0",
    "@keystone-alpha/keystone": "^10.3.0",
    "cross-env": "^5.2.0"
  }
}

having trouble getting keystone5 started.
https://v5.keystonejs.com/quick-start/
the install worked fine.
npm run dev is throwing:
ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
✖ Initialising Keystone instance
TypeError: Cannot read property 'filter' of undefined
    at intersection (/path/to/mysite/node_modules/@keystone-alpha/utils/dist/utils.cjs.dev.js:83:56)

i couldnt find a solution from googling.

**Comment by hkovacs** [comment]
oops... ctrl+enter did me in... will post full details

**Comment by timleslie** [comment]
Thanks for the bug report, @hkovacs. We just published a new version of the `create-keystone-app` package (`1.1.0`) which should fix this problem. If you're on that version and still seeing the problem feel free to re-open this issue.

**Comment by hkovacs** [comment]
works! thanks
