### ISSUE TITLE
Upgrade to Next.JS v9

### ISSUE THREAD

**Issue by MadeByMike** [keystonejs/keystone-5#1670]
- [ ] Upgrade the Admin UI App
- [x] Upgrade the NextJS App
- [ ] Upgrade demos

Easy ;)

**Comment by jesstelford** [comment]
The Admin UI doesn't currently use Next.js, so that one can be checked off already 🎉 😆

**Comment by MadeByMike** [comment]
Hang on it doesn't!?! Should it?

**Comment by mitchellhamilton** [comment]
`@keystone-alpha/app-next` already uses next 9 and has done for a while

**Comment by MadeByMike** [comment]
We nailed it!

**Comment by gautamsi** [comment]
> Hang on it doesn't!?! Should it?

see #867 and #822 for history

**Comment by gautamsi** [comment]
I do need the #1447 which was partially done in  one of the two closed PR I referenced above.

**Comment by JedWatson** [comment]
So the scope of this is just upgrading Keystone's dependency on Next to 9 for the `NextApp`, which is done ✅
