### ISSUE TITLE
Blog Demo throws type error trying to Initialising Keystone instance

### ISSUE THREAD

**Issue by cdlethem** [keystonejs/keystone-5#1685]
# Bug report

## Describe the bug

The blog demo exits with a type error when trying to launch

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:1080:7)
    at new LocalFileAdapter (/home/colin/node/keystone-5/packages/file-adapters/lib/local-file.js:7:21)
    at Object.<anonymous> (/home/colin/node/keystone-5/demo-projects/blog/schema.js:29:21)
```

I dug into it a bit and found that the LocalFileAdapter constructor expects arguments 'src' and 'path' but in /demo-projects/blog/schema.js it is instantiated with 'directory' and 'route'.

Changing these attributes to the proper name fixes this issue. I'm not sure if this is worth a pull request on its own, or if my fix is even the preferred way to go, so I'm putting it here

## To Reproduce

Steps to reproduce the behaviour. Please provide code snippets or a repository:

1. Clone github repository
2. run 'bolt'
3. create .env file
4. run 'bolt demo blog dev'

## Expected behaviour

Blog demo starts

## Screenshots

/demo-projects/blog/schema.js

![image](https://user-images.githubusercontent.com/21153126/65383043-8ece2c80-dd41-11e9-946f-248e746df2f8.png)

## System information

- OS: Windows 10 WSL Ubuntu 18.04

**Comment by jesstelford** [comment]
Thanks for looking into that for us! Your fix sounds exactly right - do you want to open a PR then we can merge & release it?

The files you're looking for are in: https://github.com/keystonejs/keystone-5/tree/master/packages/create-keystone-app/example-projects

**Comment by cdlethem** [comment]
No problem! I just opened a pull request. 

> The files you're looking for are in: https://github.com/keystonejs/keystone-5/tree/master/packages/create-keystone-app/example-projects

Unless I'm missing something, I don't think there's anything to do with the files there. This PR is just about the blog demo app here https://github.com/keystonejs/keystone-5/tree/master/demo-projects
