### ISSUE TITLE
File type not working

### ISSUE THREAD

**Issue by CPoncet** [keystonejs/keystone-5#1690]
# Bug report

## Describe the bug

I can't get the File type to work. 

Whenever I try to upload a file through the Admin UI, I get a
`GraphQL Error - Nested errors occured` pop-up

and a console DeprecationWarning 
`File upload property 'stream' is deprecated. Use 'createReadStream()' instead.`

And of course the file is not saved.

## To Reproduce

I'm using the Mongoose adapter. The database is on MongoDB Atlas on a free tier.

1. When installing, I used the Starter app (Users + authentication)
2. Created admin user by removing access + authStrategy
3. Created a 'Document' List, using the File type:

```
keystone.createList("Document", {
  fields: {
    name: { type: Text, isRequired: true },
    file: { type: File }
  }
});
```
4. When trying to add a new 'Document', I can click on upload, choose a file but when clicking "create", nothing happens. If I create a 'Document' only with a name, and try to edit it to add the file, it's not working either. On the database side, it puts a `null` value on the file field.

## Expected behaviour

I'd like to be able to add and store files obviously :)

## System information

- OS: macOS
- Browser (if applies): tested on Chrome & Firefox

**Comment by jesstelford** [comment]
D'oh, that `Nested errors occurred` message is pretty useless. Sorry!

Are you able to share a minimal reproduction?

It'd also be helpful if you could update your issue to follow the bug report template: https://raw.githubusercontent.com/keystonejs/keystone-5/master/.github/ISSUE_TEMPLATE/1.Bug_report.md

**Comment by MadeByMike** [comment]
Hi @CPoncet, you will need to define a file adapter. Here is the minimum setup:

```js
const { Text, File } = require('@keystone-alpha/fields');
const { LocalFileAdapter } = require('@keystone-alpha/file-adapters');
const fileAdapter = new LocalFileAdapter({
  src: `./uploads`,
  path: `/uploads`,
});

keystone.createList('File', {
  fields: {
    attachment: { type: File, adapter: fileAdapter },
  },
});
```

The documentation on this definitely needs to be updated!

I'll open a PR on that shortly. The extra information really helps, thank you!
