### ISSUE TITLE
Accessing related items in labelResolver

### ISSUE THREAD

**Issue by colorfulfool** [keystonejs/keystone-5#1694]
Hi,

Is there any way at all to access fields of related items in `labelResolver`?

```js
keystone.createList('Song', {
  fields: {
    title: { type: Text },
    artist: { type: Relationship, ref: 'Artist' }
  },
  labelResolver: (song) => `${song.artist} -- ${song.title}`
})
```

If not, is it especially hard to add? I'm new to Node.js, but would take a crack at it if chances are good.

**Comment by timleslie** [comment]
If you have a look in https://github.com/keystonejs/keystone-5/blob/6f90101df1652b03f6d6f29c0c6eebf88fc70509/test-projects/basic/index.js#L164 there's an example of how to do this.

The `labelResolver` callback provides the item (in your case `song`) as the first argument, but you also get a few other arguments which give you the ability to execute any other query you might want to obtain more deeply nested data.
