### ISSUE TITLE
Write CONTRIBUTING.md

### ISSUE THREAD

**Issue by dominikwilkowski** [keystonejs/keystone-5#172]
What we want to capture is:

## What you need to do to add a new feature:
- [ ] New tests have been written
- [ ] A `docs/[feature].md` file has been added that documents the feature for user-land
- [ ] An issues has been written to detail what this feature is

## What is needed for a PR to merge:
- [ ] Tests have to pass for a PR to merge
- [ ] The issue is connected to this PR (via [commit or otherwise](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] At least one approval from another contributor that is not the author
- [ ] The docs file has been added for userland

**Comment by dcousens** [comment]
Marking as done... re-open if otherwise
