### ISSUE TITLE
Custom Pages context/props

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#1737]
I see that we render the custom pages without any admin-ui context in it. I see that I can use `useQuery` and `useMutation` to work with AdminUI GraphQL. (useQuery and useMutation from `react-apollo-hooks`, pending PR #1701 for official apollo hooks usage)

I also found that I can also import `useAdminMeta` as follows and do some of the things already possible with admin-ui.
```js
import { useAdminMeta } from '@keystone-alpha/app-admin-ui/client/providers/AdminMeta';
``` 

May I propose that we add adminMeta as props when rendering custom pages along with simplified export of `useAdminMeta` hook in `@keystone-alpha/app-admin-ui/client` or a new package `@keystone-alpha/hooks` for better consumption of admin ui data in the custom page. Having props will also help when anyone writes class component (for their reason).

I will create a PR for this.

**Comment by MadeByMike** [comment]
I'm a little confused about what you're suggesting here. Technically I understand but I haven't done much with custom pages so I don't think I understand why or what this will enable. 

I'm going to add the `needs-clarification` label :) until we get a bit more info. I'm sure the PR will help me understand better but if you can also explain how data from `useAdminMeta` might be used in a custom page I'm sure it would help people less familiar... or just help me. Either way is good :)

**Comment by VinayaSathyanarayana** [comment]
There is a need to document Custom Actions Vs Custom Pages

**Comment by MadeByMike** [comment]
@gautamsi if you want to export `useAdminMeta` from `@keystone-alpha/app-admin-ui` I'll approve that PR.
