### ISSUE TITLE
Enforce "Uniqueness" of fields

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#176]
eg;

```javascript
keystone.createList('User', {
  fields: {
    email: { type: Text, unique: true },
  },
});
```

Which enforces only one `User` per email address.

**Comment by dcousens** [comment]
It appears to have been renamed to `isUnique`,  but is this enforced at the moment?

**Comment by dcousens** [comment]
From reading https://github.com/keystonejs/keystone-5/issues/433 , this is completed.
Re-open if not.
