### ISSUE TITLE
Clarify Node / Browser support, JS standards

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-5#214]
Follow-on task from my comment on #203 

Document:

* Supported Node version
* Supported Browsers
* Any features that we want to block (should be protected by ESLint where possible)

An example of the last is, if we're supporting IE 11 but not supporting async functions in the client-side code, we need to block that with an ESLint rule and document why.

Conversely, if we are, we should start building a guide on our code standards; i.e encouraging async functions.

**Comment by MadeByMike** [comment]
I'm not sure documenting this is required in 2019. We have a babel config that builds for the last 2 versions of major browsers. I think that is adequate. If specific bugs are raised that relate to a required browser feature we can say, "The AdminUI requires a browser that supports X" where X is the feature. 

For node versions I'm not as familiar with how this is normally done but I took a look at the readme of a handful of major OS projects and I don't see any explicitly listing node versions.... let's treat bugs as they come and add a note about versions if the need arises.
