### ISSUE TITLE
Improve documentation strategy

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#219]
In order to continually improve our documentation strategy, it will help to have a framework in which to think about things. This slide gives a nice example of the different types of documentation we will need to generate, and how they relate to each other.

<img width="1190" alt="screen shot 2018-08-14 at 9 10 26 am" src="https://user-images.githubusercontent.com/616382/44062983-f6623500-9fa1-11e8-89b8-4653d073f8a8.png">

Watch the full talk [here](https://www.youtube.com/watch?v=t4vKPhjcMZg).

Some short term items we can start working on are:

- [ ] Reference: Generate inline docs for the graphQL API which can be access through the `graphiql` interface (possibly linking out to more detailed resources)
 - [ ] How-to: Provide code snippets for how to do certain things, such as creating lists with relationships, etc.
 - [ ] FIXME: This list can and should be extended.

**Comment by MadeByMike** [comment]
We have a doc strategy document. I think we can close this issue?
