### ISSUE TITLE
Mapping the Relationship field type onto relational DBs

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#330]
KS 5 models it's [`Relationship` field type](https://github.com/keystonejs/keystone-5/tree/master/packages/fields/types/Relationship) after the [KS 4 type of the same name](https://github.com/keystonejs/keystone/tree/master/fields/types/relationship). In the Mongoose adapter, fields of this type store either a single ID field or an array of IDs when `many: true` is set, thereby supporting one-to-many and many-to-many relationships.

In a relational DB, many-to-many relationships are usually modelled using a associative/junction/link table. How then, should we implement this type of relationship for the Knex adapter (#297)? 

I believe our options are...

1. **Follow the current strategy and use array based relationships in the relational/Knex adapter**
Postgres has excellent array support but using them for relationships might be counter intuitive a relational context and probably (?) introduce a performance penalty. Other DB platforms require serialisation to support anything resembeling an array (eg. [MySQL](https://99webtools.com/blog/how-to-store-array-in-mysql), [SQLite](https://stackoverflow.com/questions/3005231/how-to-store-array-in-one-column-in-sqlite3)) which either breaks many-to-many relationships or results in terrible performance.

1. **Refactor the current field type to always use an associative table/collection**
Really not ideal for Mongo due to lack of (performant) joins. Arrays of IDs actually make sense in the "key-value-like" document store land of Mongo.

1. **Use arrays in Mongo and an associative table in relational DBs within the current field type**
This is probably workable but supporting both methods will add significant complexity to the field type implementation, especially given our desired relationship workflows (#251).

1. **Implement a different relationship type (or types) for relational DBs** 
These two types of data persistence represent fundamentally different paradigms which reasonable and intuitively model relationships in different ways. Trying to fit one-to-many and many-to-many for both relational and document store data layers into a single field type is unnecessary and possibly undesirable.

For reference, KS Next didn't follow the [`Relationship` field type of KS 4](https://github.com/keystonejs/keystone/tree/master/fields/types/relationship), opting instead for a solution that more closely reflected the underlying structure with the [`ForeignKey`](https://github.com/Thinkmill/groki-platform/tree/master/common/keystoneNext/fieldTypes/ForeignKey) and [`RelatedChildren`](https://github.com/Thinkmill/groki-platform/blob/master/common/keystoneNext/fieldTypes/RelatedChildren/README.md) field types (with the intention to add a [`RelatedItem`](https://github.com/Thinkmill/groki-platform/blob/master/common/keystoneNext/fieldTypes/RelatedItem/README.md) type for one-to-one relationships).

**Comment by jesstelford** [comment]
This has been implemented.
