### ISSUE TITLE
Expand social signin/auth functionality

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#331]
Some work's already been done on social auth to [support twitter](https://github.com/keystonejs/keystone-5/tree/master/projects/twitter-login).

This area of the system should be expanded to support more auth providers.

Worth noting the [plugin Johnny Estilles built for KS 4](https://github.com/JohnnyEstilles/keystone-social-login). It supports Facebook, Twitter, Google (OAuth) and GitHub. See also the [feature requests/discussion in KS 4](https://github.com/keystonejs/keystone/issues/535).

**Comment by MadeByMike** [comment]
Closing in favour of  #878
