### ISSUE TITLE
Address the "filtering by related things" problem

### ISSUE THREAD

**Issue by molomby** [keystonejs/keystone-5#376]
Let's say you have a list `posts` with a related field `author` (that links to the `authors` list). Currently, the "simple search" functionality (#319) available from the admin UI won't dereference this relationship. So if you filter by "Jane" in the admin UI, you'll only get `posts` with "Jane" in the name, not posts where the _author_ has "Jane" in _their_ name.

Ideally, Keystone would be able to apply these "simple search" filters to related collections and apply them to items in the list being viewed.

Note, this functionality is closely related to, and dependant on, the "Implement configurable search fields" (#343) but is _a distinct piece of work_.

**Comment by MadeByMike** [comment]
Closing as dupe. Moved all information here over to #352
