### ISSUE TITLE
Add deploy hooks to ci

### ISSUE THREAD

**Issue by lukebatchelor** [keystonejs/keystone-5#4]
Happy to pick setting up a CI process for this.

What are some of the things we'd like?

* [x] Run linting
* [x] Make some tests? ;P (Jest / Ava?)

**Super nice to haves**
* [ ] Deploy the frontend somewhere
  * Maybe have all static front ends point to a the same demo backend? Maybe that wont work because we really need to be generating most of that...
* [ ] deploy backend preview to heroku?

Feel free to suggest more things and I'll pick it up soon

**Comment by JedWatson** [comment]
@mitchellhamilton I think you've got this, feel free to close this issue when you're happy with the setup

**Comment by MadeByMike** [comment]
This is really only and mostly done. I don't think the "Super nice to haves" are relevant anymore so closing
