### ISSUE TITLE
Fields overlap in list view when many columns are selected

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#424]
If we select too many columns then we run out of space to display the individual cell contents.

<img width="1157" alt="screen shot 2018-10-10 at 9 19 34 am" src="https://user-images.githubusercontent.com/616382/46702130-b7166580-cc6d-11e8-86b5-91a25e8f9ee1.png">

In Keystone 4 we used truncation to make things fit, which seems like a good solution to me. If anyone has different ideas for how to solve this issue then we can always try something else.

<img width="1176" alt="screen shot 2018-10-10 at 9 23 58 am" src="https://user-images.githubusercontent.com/616382/46702338-6f440e00-cc6e-11e8-89a6-b63999ad56e0.png">

**Comment by MadeByMike** [comment]
Solved with truncated text.
