### ISSUE TITLE
Sort out publishing auth

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone-5#453]
Publishing!

To publish packages to npm I:

1. Disabled 2fa
2. Published
3. Re-enabled 2fa

This is a terrible workflow and shouldn't be repeated.

**Engineering challenge** (easy): Bolt spawns a process to run publish, and I couldn't hack it to accept my `otp` token even in a very manual way. Likely an error in rushed engineering efforts.

**Challenge** (hard): 2fa keys last 60 seconds, however running `publish` may take longer than that, so even if we can pass in an `otp` option, we may need to run publish multiple times to get everything published.

Note that if you have 2fa on, you can't use a token to publish:
https://npm.community/t/publish-on-ci-with-2fa/534

**(A) Solution**:
Have an account that has 2fa login,  and a token that is associated with an IP range that publishes. This should likely not be any individual's personal account.

Open to other options also

**Comment by jesstelford** [comment]
This is working in the latest versions of `changeset`
