### ISSUE TITLE
"Markdown" Field

### ISSUE THREAD

**Issue by VinayaSathyanarayana** [keystonejs/keystone-5#475]
We should consider having a markdown field with the following

* Github style marking of code with ```
* @ Mentions
*  '#' links to other Lists like Posts etc

**Comment by dcousens** [comment]
See https://github.com/keystonejs/keystone-5/issues/616

**Comment by molomby** [comment]
This is a thing now: `@keystone-alpha/fields-markdown`; see #316 and #1357.

No support for `@` mentions or links to other keystone item though (other than the standard Markdown link syntax).
