### ISSUE TITLE
encodeSortBy not working with non-virtual fields

### ISSUE THREAD

**Issue by ticidesign** [keystonejs/keystone-5#487]
When trying to remove all non-virtual fields from the Columns dropdown option we get this error:

![screen shot 2018-11-08 at 10 26 59 am](https://user-images.githubusercontent.com/289889/48167820-1769f700-e341-11e8-8f65-0bcea5e5881d.png)

**Comment by MadeByMike** [comment]
Tested and looks to be resolved
