### ISSUE TITLE
Hooks - rollback on failure

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#534]
If a mutation fails we need to be able to rollback any operations which happened during the hooks leading up to the failure.

We need to provide a mechanism for this rollback, but it has not yet been decided what that mechanism should be.

The initial hairy session for hook design came up with the idea of providing a `addRollbackStep` function which could be called from hooks, which would collect all the rollback functions to be executed on failure.

Subsequent review of this in the context of nested mutations and the difficultly of tracking rollbacks introduced the idea that perhaps a simpler design would be that each field type/field/list could have a `cleanup` (or similar) hook and it would be up to the system designer to keep track of what needed to be called in the case of failure.

**Comment by jesstelford** [comment]
See also: https://github.com/keystonejs/keystone-5/issues/211

**Comment by MadeByMike** [comment]
I've updated #211 and am now closing this as a dupe
