### ISSUE TITLE
Website smol work

### ISSUE THREAD

**Issue by Noviny** [keystonejs/keystone-5#630]
Had a bunch of very small tasks to do on the docs website. Listing them here. Recommend requests for the website be added here unless it is going to be a massive change.

- [ ] On page load, scroll sidebar to show where you are
- [ ] Make selected sidebar item more obvious (background colour?)
- [x] Revisit preview logic in `gatsby-config.js`
	preview is odd (section: ... or id: ....), not what I expected
- [x] Make our `contributors` mention on the splash link somewhere to show list of contributors
- [x] We're using `em` in some places and `rem` in other places. for styling. Check why and unify
- [x] Make dropdown keyboard friendly
- [x] Refactor search component and page so the shared parts are shared
- [x] Make sure all files that export react components start with a capital (I think this is pascal case)
- [x] Add favicon of keystone logo
- [ ] Ensure links are correct (known wrong ones are in `/docs/hooks` to `/docs/hooks-api` instead goes to `/docs/hooks/hooks-api`) as well as some hash links
- [x] Make site mobile-friendly
- [x] Move tutorials to be under `docs/` folder, move guides to `docs/guides`
- [x] Nail footer bar to the bottom of the page even on short pages
- [x] Move existing docs into either guides or tutorials
- [ ] Make packages docs display at a lower information level, distinguishable from guides/tutorials
- [x] Resolve website needing its own yarn install (add it back to the monorepo)
- [x] Pass a custom link component to mdx which uses gatsby-link for internal components

**Comment by MadeByMike** [comment]
I've audited what was here and it looks like it's either done or the site has evolved since this issues was created. Website will remain WIP and more to improve but I feel like this list is no longer useful. Closing :)
