### ISSUE TITLE
Generate documentation for Field Types

### ISSUE THREAD

**Issue by mitchellhamilton** [keystonejs/keystone-5#740]
I was about to start writing documentation for more field types but I think it might be worth seeing how much of documentation we can generate. We could show the GraphQL schema that each field type generates and maybe use some of the information that we use in the Admin UI in the docs, e.g. the filter types have names that are used in the GraphQL schema and labels for the Admin UI, we could show those labels. Also, if we write a lot of the documentation in the field types, we could reuse it in the GraphQL schema so it's available in the GraphQL playground. Anyone have thoughts on this?

cc @Noviny Do you have any thoughts on this based on your experiences with extract-react-types? Were there things that were very useful to generate things that you think would translate well to field types? Were there things that weren't valuable to generate?

**Comment by molomby** [comment]
Presumably we could extract much of the info we wanted though the implementation and field adapter interfaces without needing to parse the code itself. Eg. fire up an instance of the field, call `getQueryConditions()` and see what comes back; mock up a knex table schema build and pass it though `addToTableSchema()`, see what gets added, etc.

If this was packaged up well, any 3rd-party developer could pull it in as a dependancy and generate docs for their field types.

It sounds like the tooling should dump the info it collects into a json file maybe? Might make it easy to verify/version control/curate the specifics. The json could then be consumed by components in the mdx docs and the admin UI, etc. Does that sound right?

**Comment by MadeByMike** [comment]
We now have documentation for almost all field types with a few needing update. I'll priorities this but I think auto generated documentation is not priority anymore.
