### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#836]
As an open source project, we should adopt a code of conduct and ensure that we are in a position to respond to any possible violations.

The [Contributor Covenant](https://www.contributor-covenant.org/) is one possible options, but others exist, e.g. http://citizencodeofconduct.org/, https://www.djangoproject.com/conduct/

If we decide to adopt the Contributor Covenant we will need to decide on a contact email address to include in the document and ensure that any emails to that address get seen by a real human who is in a position to address the concerns.

**Comment by JedWatson** [comment]
This has been added 👍
