### ISSUE TITLE
[RFC] Delay List initialization until keystone.conenct(), Helps plugin/extension scenario

### ISSUE THREAD

**Issue by gautamsi** [keystonejs/keystone-5#842]
## Custom Field option to be used by plugins/extension

Currently there is no documented way to add custom field outside or `keystone.createList` probably you can not do that either due to how they are tightly coupled with schema generation.

While working on Twitter login fix (in #801) I was thinking about how to achieve the scenario on #331.

A plugin/extension point needed for such scenario. One of them is creating custom fields in lists. For example, we may not need to code twitter (or facebook e.t.c) specific fields in User list, they could be generated by  specific `AuthStrategy`. (This scenario may even cover the `PasswordAuthStrategy` to create password and username fields)

### Caveat in current code:
List fields are initialized inside Keystone `createList` method. Once created, you may not (or should not) change the list fields, all the meta information is finalized during `list.initFields`. 

If we can delay the execution of this until `keystone.conenct()`/`server.start()` then any plugin/extension can have the opportunity to add related fields information in the list.

I tried to make twitter login work again in #801. went ahead and added another commit 08375b5d5cd49bdbf93101ebaaa5b795966d599d and crated a [draft pull request  in my own fork for reference](https://github.com/gautamsi/keystone-5/pull/1) . 

### How did I achieve this?
- move `list.initFields` call inside `keystone.connect`
- Had to make WebServer package delay the app.use commands which needs initialized fields, moved it to another function and called it right after `keystone.connect()` inside `server.start()`
- Also had to create a processing queue for `app.use` in web server. this is needed to correct the order of middlewares and routes. 
- queued app.use call instead of calling it directly inside Twitter Auth Strategy and twitter.js in test project. 
- removed twitter fields from "User" list, also added a custom text field inside server.js of test project.

I am sure someone can figure out smarter way to achieve this. I am just putting this here for starting discussion in this direction. 

here is the result of this experiment:
- twitter auth still works, 
- fields now generated and added by TwitterAuthStrategy rather than inside User list creation.
- new fields are visible in admin ui and graphiql

## Possibility
1. Plugin/extension can be created in userland
2. Plugins can have their own workflow like "Publishing" scenario"
3. Plugins can create custom field type and corresponding view bundled with them

### Admin Ui enhancement needed
1. Add marking that this is plugin generated field (tooltip or info button which can pop out plugin information)
2. plugin may have option to make it read only

**This will also help in plugins adding their own custom field Type and views**

### Screenshots:

1. When added custom field "TestCustom" while Twitter auth is disabled

![Screen Shot 2019-03-16 at 2 45 10 AM](https://user-images.githubusercontent.com/5769869/54463933-c066a980-479a-11e9-8b48-b8fd599974d9.png)

2. When enable twitter auth and have fields created by TwitterAuthStrategy
![Screen Shot 2019-03-16 at 2 52 13 AM](https://user-images.githubusercontent.com/5769869/54464003-fd32a080-479a-11e9-80ec-1873a75d494f.png)

2.1 graphql schema inside graphiql when using twitter auth custom fields
![Screen Shot 2019-03-16 at 2 55 24 AM](https://user-images.githubusercontent.com/5769869/54464026-14718e00-479b-11e9-8dba-3440036faeb7.png)

**Comment by gautamsi** [comment]
@timleslie any thoughts on this, this will also help in streamlining all the server middleware mount. Instead of `<expressapp>.use/all` etc. we do `<keystone server>.use/all`. It gets queued until `keystone.connect()`

**Comment by MadeByMike** [comment]
@gautamsi we've discussed this a few times with the code team and we believe that `createList` be the only way to add things to a list and in general we don't want to delay the initalization of lists. We need to capture any new use-cases for a more general plugin architecture in: #1489
