### ISSUE TITLE
Relationships: Document filtering abilities

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#85]
See https://github.com/keystonejs/keystone-5/pull/81 for context

- [ ] The MongoDB JOIN/Pipeline code: https://github.com/keystonejs/keystone-5/issues/223
- [x] The GraphQL API
- [ ] Various examples
- [x] `AND`/`OR` filtering: https://github.com/keystonejs/keystone-5/issues/224

**Comment by MadeByMike** [comment]
@jesstelford could I get clarification on what it means to document the MongoDB JOIN/Pipeline. I think we've covered off most of the rest.

**Comment by jesstelford** [comment]
Yep, this one is done 👍
