### ISSUE TITLE
Frontmatter in READMEs doesn't play nice with npm website

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#888]
It'd be great if we could make this nicer somehow.
<img width="663" alt="Screen Shot 2019-03-22 at 9 17 03 am" src="https://user-images.githubusercontent.com/616382/54788522-632f9400-4c83-11e9-91b6-0be799e50330.png">

**Comment by mitchellhamilton** [comment]
We fixed this a while ago by putting the frontmatter into comments
