### ISSUE TITLE
Plural and singular lists rely on the english language

### ISSUE THREAD

**Issue by dominikwilkowski** [keystonejs/keystone-5#893]
So I get that we need plural in our GraphQL queries. `Mentos` will fail because well... the plural is the same word. But should it not be over-writable? We already provide `singular` and `plural` as an option in `createList` but this will still fail:

```js
keystone.createList('Mentos', {
  singular: 'A Mentos',
  plural: 'Many Mentos',
  fields: { name: { type: Text } },
});
```

So I would have to do:

```diff
- keystone.createList('Mentos', {
+ keystone.createList('Mento', {
  singular: 'A Mentos',
  plural: 'Many Mentos',
  fields: { name: { type: Text } },
});
```

But more importantly what happens when I am not an english speaker? Or I create a Keystone site for a client who is not an english speaker.

Given the german word `Tisch` which has a plural of `Tische`:

```js
keystone.createList('Tisch', {
  singular: 'Tisch',
  plural: 'Tische',
  fields: { name: { type: Text } },
});
```

We get `Tisches` and it ignored the `singular` and `plural` option in our List. I suggest to either slugify the `singular` and `plural` options and use them if they are supplied or add `singularKey` and `pluralKey` options.

**Comment by jesstelford** [comment]
Would love to get this right!

It sounds like there's 2 things going on here:

1. A bug in the english-supported `singular` / `plural` config options not being applied correctly.
2. Lack of support for any other language / some edge cases for English.

I've not overly familiar with i18n, but I would assume that most languages have different rules for what they consider a plural and a singular. I wonder if those rules are codified anywhere that we can leverage?

**Comment by MadeByMike** [comment]
@jesstelford @dominikwilkowski I think this edge-case is now resolved with the ability to set query names?

I would expect the queries to ignore singular and plural options to be used for labels and ignored by the queries. Use `itemQueryName` and `listQueryName` for GQL.

I'm updating docs to reflect this now.
