### ISSUE TITLE
Decimal type isn't displayed in Admin UI or Reachable via single query

### ISSUE THREAD

**Issue by wesbos** [keystonejs/keystone-5#911]
Using this code: 

```js
keystone.createList('Shoe', {
  schemaDoc: 'A list of things which need to be done',
  fields: {
    title: { type: Types.Text, schemaDoc: 'The title of the shoe' },
    price: { type: Types.Decimal, schemaDoc: 'The price of the shoe' },
  },
});
```

Saving a price of `100.42` is saved in the DB (confirmed in graphiql), but the admin UI shows the input as empty.

I think this has something to do with the singular query because `allShoes` shows the price in graphiql, but shoe(where: { id: "abc"}) returns in an error:

Error here: 
<details>
{
  "errors": [
    {
      "message": "String cannot represent value: { _bsontype: \"Decimal128\", bytes: <Buffer 42 27 00 00 00 00 00 00 00 00 00 00 00 00 3c 30> }",
      "locations": [
        {
          "line": 9,
          "column": 5
        }
      ],
      "path": [
        "Shoe",
        "price"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: String cannot represent value: { _bsontype: \"Decimal128\", bytes: <Buffer 42 27 00 00 00 00 00 00 00 00 00 00 00 00 3c 30> }",
            "    at GraphQLScalarType.serializeString [as serialize] (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/type/scalars.js:159:9)",
            "    at completeLeafValue (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:641:37)",
            "    at completeValue (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:587:12)",
            "    at completeValueCatchingError (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:503:19)",
            "    at resolveField (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:447:10)",
            "    at executeFields (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeValue (/Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:598:12)",
            "    at /Users/wesbos/Dropbox/demos/keystone-test/node_modules/graphql/execution/execute.js:500:16",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      },
      "uid": "cjtk5uv1r00020cufay8lamv4",
      "name": "GraphQLError"
    }
  ],
  "data": {
    "allShoes": [
      {
        "title": "AirMax",
        "price": "100.50",
        "id": "5c94f0eec2e1c3ca8cfbd6ee"
      }
    ],
    "Shoe": {
      "title": "AirMax",
      "price": null
    }
  },
  "extensions": {}
}
</details>

<img width="1396" alt="Screen Shot 2019-03-22 at 10 31 04 AM" src="https://user-images.githubusercontent.com/176013/54829813-9e36c500-4c8d-11e9-854b-30ac84c23c61.png">

**Comment by timleslie** [comment]
Hi @wesbos, thanks for the bug report. I'll take a look into it.

**Comment by MadeByMike** [comment]
![image](https://user-images.githubusercontent.com/1320567/64938332-e03d6e00-d8a0-11e9-9cac-81576ed113bb.png)


@wesbos It looks like this one has been resolved in the course of things. Sorry nobody got back to you!
