### ISSUE TITLE
"Tutorials" before "Guides" in main navigation 

### ISSUE THREAD

**Issue by simonswiss** [keystonejs/keystone-5#924]
The mere fact that I can read this in the guides page...

> If this if your first time using Keystone, we recommend working through the tutorials to get a feel for how Keystone works and how to set up your very first project.

... suggests that the tutorials should come **before** the technical guides in the navigation.  It is the case in the sidebar, but not in the main nav.

I think docs should always cater for newcomers first - since regular users will learn where to find things after their first visit.

Happy to do a PR for that.

![image](https://user-images.githubusercontent.com/485747/54886948-b7d04a80-4ee1-11e9-9822-7b8eaf5aa7e2.png)

**Comment by mitchellhamilton** [comment]
Sounds good, a PR would be great!

**Comment by MadeByMike** [comment]
Guides for the moment represents _both_ tutorials and guides. The reality is until we have enough documentation and examples to support both this is better in one section
