### ISSUE TITLE
Define our "examples" strategy

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#950]
From #948

> this refactor is 100% a thing I can imagine a new user doing, and would encourage it as they build this example out into a more full featured application!
> 
> And it's definitely a thing I can imagine someone doing as a way to build their understanding of a Keystone app / how best to structure their own app.
> 
> But I think it's something the developer should do themselves, not something we should do for them. There's a limit here: if we add more features to the blog demo, the index.js file might just get too big and hard to follow. At that point we should think about either taking Zeit's next/examples method where it's a seperate folder per small feature, or break this project out into its own repo with its own documentation and leave it as one way to build a KS5 app.

We need to be clear on how much we want to hand hold, and how much we want to be left up to the developer, then make sure all our examples hit that mark.

Personally I'm a big fan of Zeit's next/examples folders: I often find myself with a very specific task at hand that I can easily find an answer to there.

**Comment by JedWatson** [comment]
> I'm a big fan of Zeit's next/examples folders

💯

**Comment by molomby** [comment]
Relates (somewhat) to the [demo project ideas](https://paper.dropbox.com/doc/Demo-Projects--APi5x2dTUHbRo08999b1CboRAg-ejN2zD2GUd5VMtJ5v0tSG) we came up with.

**Comment by gautamsi** [comment]
We should rename the `demo-projects` to `examples` asap and use this as part of downloading examples through cli.

I am pushing `examples` folder to my PR #1024 now, not changing existing one though.

**Comment by timleslie** [comment]
@gautamsi I'm not sure that renaming the `demo-projects` is something we want to do. If we do, it should be done in a separate PR, rather than mixed in with other feature development. At the moment I don't see any reason to change the name though.

**Comment by MadeByMike** [comment]
I don't think we need to define this now as it is documented in the way the CLI uses the examples. The demo project are currently used for testing and I would like the ability for the CLI to use an examples folder at the root level... but I think we can revisit this later this issue is not really actionable at the moment
